site_name: Riya Gujarathi's Website
site_url: https://spaceroborg.github.io/
theme:
  name: material
  favicon: images/taro_icon.svg
  logo: images/riya_profile.png
  language: en
  palette: 
    primary: custom
    accent: teal
  custom_dir: overrides

plugins:
  - search
  - macros
  - open-in-new-tab

site_dir: _site

not_in_nav: projects/*

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - extra.css
  
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.blocks.html

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: /fontawesome/solid/envelope
      name: Send Riya an enquiry by mail
      link: mailto:&#114;&#105;&#121;&#097;&#046;&#110;&#046;&#103;&#117;&#106;&#097;&#114;&#097;&#116;&#104;&#105;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;
    - icon: fontawesome/brands/linkedin
      name: Riya on LinkedIn
      link: https://www.linkedin.com/in/riya-gujarathi/
    - icon: fontawesome/brands/github
      name: Riya on Github
      link: https://github.com/spaceroborg

copyright: Copyright &copy; 2021 - 2025 Kimberly N. McGuire. Privacy-friendly analytics by Goatcounter
