[project]
channels = ["conda-forge"]
name = "spaceroborg.github.io"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs-material = ">=9.6.3,<10"
pyyaml = ">=6.0.2,<7"
pypdf2 = ">=3.0.1,<4"
lunr = ">=0.8.0,<0.9"

[pypi-dependencies]
mkdocs-rss-plugin = ">=1.17.1, <2"
mkdocs-macros-plugin = ">=1.3.7, <2"
mkdocs-open-in-new-tab = ">=1.0.8, <2"
bs4 = ">=0.0.2, <0.0.3"
markdownify = ">=1.1.0, <2"
