theme: minima
repository: knmcguire.github.io
title: Kimberly's personal website
author: Kimberly. N. McGuire, PhD
email: kimberleymcguire _AT_ gmail.com

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

#markdown: kramdown

markdown_extensions:
  - attr_list

header_pages:
  - lnktr.md
  - index.md
  - projects/index.md
  - press.md

twitter_username: k_n_mcguire
github_username: knmcguire
linkedin_username: knmcguire

